### ISSUE TITLE
Error when changing user department

### ISSUE THREAD

**Issue by lijiann-amazon** [aws-samples/amazon-connect-scim-user-management#2]
When changing user department from 'Agent' to 'Admin' on AzureAD, getting error on lambda. This also occurs when removing the department value from the user in AzureAD (to remove the user from the group). 

Cloudwatch log below:

`[ERROR] KeyError: 'department'
Traceback (most recent call last):
  File "/var/task/user_management_lambda.py", line 365, in lambda_handler
    scim_user = "{{\"schemas\":[\"urn:ietf:params:scim:schemas:core:2.0:User\", \"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User\"], \"id\":\"{}\",\"externalId\":\"{}\",\"userName\":\"{}\",\"active\":true,\"meta\":{{\"resourceType\":\"User\"}},\"roles\":[],\"name\": {{\"familyName\":\"{}\",\"givenName\":\"{}\"}}, \"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User\":{{\"department\":\"{}\"}}}}".format(id, user["externalId"],  user["Username"], user["LastName"], user["FirstName"], user_update['department'])      # noqa: E501`

**Comment by gopinjag** [comment]
Ensure the Attributes for the mapping section are accurate as defined here 
https://catalog.us-east-1.prod.workshops.aws/workshops/0436a9a9-18f2-4707-a629-021358df997e/en-US/2-identity-provider-scim-integration/1-create-amazon-connect-integration-with-azuread/1-azuread-application-setup-and-configuration 

Also Azure AD takes 40 minutes to sync , hence during update verify the payload . Please don't mix on demand and regular provisioning . In case this 40 mins should be reduced , follow the steps outlined in the blog 
https://aws.amazon.com/blogs/security/on-demand-scim-provisioning-of-azure-ad-to-aws-sso-with-powershell/
